name: Caller Workflow
on:
  workflow_dispatch: {}

jobs:
  dispatch2call:
    name: ${{ github.event_name }}2call
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/test-workflow.yaml
