name: Caller Workflow
on:
  workflow_dispatch: {}
env:
  caller: workflow

jobs:
  dispatch2call:
    name: ${{ github.event_name }}2call$-${{ github.path }}-
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/test-workflow.yaml
    with:
      test: ${{ github.path }}

  dispatch2call-2:
    name: Not Doing Anything Workflow
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/not-doing-anything-workflow.yaml

  env:
    name: "dump ${{ github.path }}"
    runs-on: ubuntu-20.04
    steps:
    - name: ${{ github.event_name }}
      run: echo '${{ github.event_name }}'
    - name: github
      run: echo '${{ toJSON(github) }}' | jq .
    - name: github 2
      run: echo '${{ toJSON(github) }}' | jq .
    - name: env
      run: echo '${{ toJSON(env) }}' | jq .
    - name: job
      run: echo '${{ toJSON(job) }}' | jq .
    - name: steps
      run: echo '${{ toJSON(steps) }}' | jq .
    - name: secrets
      run: echo '${{ toJSON(secrets) }}' | jq .
    - name: strategy
      run: echo '${{ toJSON(strategy) }}' | jq .
    - name: matrix
      run: echo '${{ toJSON(matrix) }}' | jq .
    - name: needs
      run: echo '${{ toJSON(needs) }}' | jq .
    - name: inputs
      run: echo '${{ toJSON(inputs) }}' | jq .
    - name: path file
      run: cat '${{ github.path }}'
    - name: env file
      run: cat '${{ github.env }}'
    - name: step_summary file
      run: cat '${{ github.step_summary }}'
    - name: state file
      run: cat '${{ github.state }}'
    - name: output file
      run: cat '${{ github.output }}'

