name: Test Workflow
on:
  workflow_call: {}

jobs:
  call:
    name: "Call (${{ github.event_name }})"
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"

  other:
    name: "Other (${{ github.event_name }})"
    runs-on: ubuntu-20.04
    if: github.event_name != 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"
    - run: echo "${{ toJSON(github) }}"
    - run: echo "${{ toJSON(env) }}"
    - run: echo "${{ toJSON(job) }}"
    - run: echo "${{ toJSON(jobs) }}"
    - run: echo "${{ toJSON(steps) }}"
    - run: echo "${{ toJSON(secrets) }}"
    - run: echo "${{ toJSON(strategy) }}"
    - run: echo "${{ toJSON(matrix) }}"
    - run: echo "${{ toJSON(needs) }}"
    - run: echo "${{ toJSON(inputs) }}"
