name: Test Workflow
on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  call:
    name: ${{ github.event_name }}
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"

  dispatch:
    name: ${{ github.event_name }}
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"

  dispatch2call:
    name: ${{ github.event_name }}2call
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/test-workflow.yaml
