name: Test Workflow
on:
  workflow_call: {}

jobs:
  call:
    name: ${{ github.event_name }}
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"

  other:
    name: ${{ github.event_name }}
    runs-on: ubuntu-20.04
    if: github.event_name != 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"
