name: Test Workflow
on:
  workflow_call: {}

jobs:
  call:
    name: "Call (${{ github.event_name }})"
    runs-on: ubuntu-20.04
    if: github.event_name == 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo "${{ github.event_name }}"

  other:
    name: "Other (${{ github.event_name }})"
    runs-on: ubuntu-20.04
    if: github.event_name != 'workflow_call'
    steps:
    - name: ${{ github.event_name }}
      run: echo '${{ github.event_name }}'
    - name: github
      run: echo '${{ toJSON(github) }}' | jq .
    - name: env
      run: echo '${{ toJSON(env) }}' | jq .
    - name: job
      run: echo '${{ toJSON(job) }}' | jq .
#    - name: jobs
#      run: echo '${{ toJSON(jobs) }}' | jq .
    - name: steps
      run: echo '${{ toJSON(steps) }}' | jq .
    - name: secrets
      run: echo '${{ toJSON(secrets) }}' | jq .
    - name: strategy
      run: echo '${{ toJSON(strategy) }}' | jq .
    - name: matrix
      run: echo '${{ toJSON(matrix) }}' | jq .
    - name: needs
      run: echo '${{ toJSON(needs) }}' | jq .
    - name: inputs
      run: echo '${{ toJSON(inputs) }}' | jq .
